services:
  fl-client1:
    build: .
    container_name: fl_client_1
    command: python client_worker.py
    environment:
      CLIENT_ID: "1"
      SERVER_URL: http://fl-scam-api:8000
      DATA_PATH: data/client1_data.csv
      LOCAL_EPOCHS: 5
      BATCH_SIZE: 32
      LEARNING_RATE: 0.01
      POLL_SECONDS: 5
    volumes:
      - ./data:/app/data
    networks:
      - fl-monitoring-net

networks:
  fl-monitoring-net:
    external: true
    name: fl-sc_fl-monitoring-net
