services:
  fl-scam-api:
    build: .
    container_name: fl-scam-api
    command: uvicorn server_api:app --host 0.0.0.0 --port 8000
    environment:
      NUM_CLIENTS: 2
      N_ROUNDS: 10
      INPUT_DIM: 10
    ports:
      - "8000:8000"
    volumes:
      - ./checkpoints:/app/checkpoints
    networks:
      - fl-monitoring-net

  prometheus:
    image: prom/prometheus:latest
    container_name: fl-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - fl-scam-api
    networks:
      - fl-monitoring-net

  grafana:
    image: grafana/grafana:latest
    container_name: fl-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - fl-monitoring-net

networks:
  fl-monitoring-net:
    name: fl-sc_fl-monitoring-net
